/* The following code was generated by JFlex 1.4.3 on 12/10/17 6:15 PM */

//java -jar JFlex.jar D:\Dropbox\Retroscope++\retroscope-lib\RQLServer\src\main\java\retroscope\rql\langspecs\rql.flex
package retroscope.rql.parser;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 12/10/17 6:15 PM from the specification file
 * <tt>D:/Dropbox/Retroscope++/retroscope-lib/RQLServer/src/main/java/retroscope/rql/langspecs/rql.flex</tt>
 */
public class Scanner implements mTokens {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;
  private static final String ZZ_NL = System.getProperty("line.separator");

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\10\1\3\1\2\1\0\1\3\1\1\16\10\4\0\1\3\1\57"+
    "\1\45\1\6\1\7\1\47\1\61\1\0\1\51\1\52\1\5\1\46"+
    "\1\70\1\44\1\42\1\4\1\11\11\12\1\66\1\67\1\64\1\63"+
    "\1\65\1\60\1\0\1\17\1\36\1\23\1\34\1\13\1\25\1\41"+
    "\1\32\1\20\2\7\1\16\1\30\1\21\1\27\1\15\1\7\1\26"+
    "\1\22\1\24\1\33\1\40\1\31\1\14\2\7\1\55\1\37\1\56"+
    "\1\50\1\35\1\0\4\7\1\43\25\7\1\53\1\62\1\54\1\0"+
    "\41\10\2\0\4\7\4\0\1\7\2\0\1\10\7\0\1\7\4\0"+
    "\1\7\5\0\27\7\1\0\37\7\1\0\u01ca\7\4\0\14\7\16\0"+
    "\5\7\7\0\1\7\1\0\1\7\21\0\160\10\5\7\1\0\2\7"+
    "\2\0\4\7\10\0\1\7\1\0\3\7\1\0\1\7\1\0\24\7"+
    "\1\0\123\7\1\0\213\7\1\0\5\10\2\0\236\7\11\0\46\7"+
    "\2\0\1\7\7\0\47\7\7\0\1\7\1\0\55\10\1\0\1\10"+
    "\1\0\2\10\1\0\2\10\1\0\1\10\10\0\33\7\5\0\3\7"+
    "\15\0\5\10\6\0\1\7\4\0\13\10\5\0\53\7\37\10\4\0"+
    "\2\7\1\10\143\7\1\0\1\7\10\10\1\0\6\10\2\7\2\10"+
    "\1\0\4\10\2\7\12\10\3\7\2\0\1\7\17\0\1\10\1\7"+
    "\1\10\36\7\33\10\2\0\131\7\13\10\1\7\16\0\12\10\41\7"+
    "\11\10\2\7\4\0\1\7\5\0\26\7\4\10\1\7\11\10\1\7"+
    "\3\10\1\7\5\10\22\0\31\7\3\10\104\0\1\7\1\0\13\7"+
    "\67\0\33\10\1\0\4\10\66\7\3\10\1\7\22\10\1\7\7\10"+
    "\12\7\2\10\2\0\12\10\1\0\7\7\1\0\7\7\1\0\3\10"+
    "\1\0\10\7\2\0\2\7\2\0\26\7\1\0\7\7\1\0\1\7"+
    "\3\0\4\7\2\0\1\10\1\7\7\10\2\0\2\10\2\0\3\10"+
    "\1\7\10\0\1\10\4\0\2\7\1\0\3\7\2\10\2\0\12\10"+
    "\4\7\7\0\1\7\5\0\3\10\1\0\6\7\4\0\2\7\2\0"+
    "\26\7\1\0\7\7\1\0\2\7\1\0\2\7\1\0\2\7\2\0"+
    "\1\10\1\0\5\10\4\0\2\10\2\0\3\10\3\0\1\10\7\0"+
    "\4\7\1\0\1\7\7\0\14\10\3\7\1\10\13\0\3\10\1\0"+
    "\11\7\1\0\3\7\1\0\26\7\1\0\7\7\1\0\2\7\1\0"+
    "\5\7\2\0\1\10\1\7\10\10\1\0\3\10\1\0\3\10\2\0"+
    "\1\7\17\0\2\7\2\10\2\0\12\10\1\0\1\7\17\0\3\10"+
    "\1\0\10\7\2\0\2\7\2\0\26\7\1\0\7\7\1\0\2\7"+
    "\1\0\5\7\2\0\1\10\1\7\7\10\2\0\2\10\2\0\3\10"+
    "\10\0\2\10\4\0\2\7\1\0\3\7\2\10\2\0\12\10\1\0"+
    "\1\7\20\0\1\10\1\7\1\0\6\7\3\0\3\7\1\0\4\7"+
    "\3\0\2\7\1\0\1\7\1\0\2\7\3\0\2\7\3\0\3\7"+
    "\3\0\14\7\4\0\5\10\3\0\3\10\1\0\4\10\2\0\1\7"+
    "\6\0\1\10\16\0\12\10\11\0\1\7\7\0\3\10\1\0\10\7"+
    "\1\0\3\7\1\0\27\7\1\0\12\7\1\0\5\7\3\0\1\7"+
    "\7\10\1\0\3\10\1\0\4\10\7\0\2\10\1\0\2\7\6\0"+
    "\2\7\2\10\2\0\12\10\22\0\2\10\1\0\10\7\1\0\3\7"+
    "\1\0\27\7\1\0\12\7\1\0\5\7\2\0\1\10\1\7\7\10"+
    "\1\0\3\10\1\0\4\10\7\0\2\10\7\0\1\7\1\0\2\7"+
    "\2\10\2\0\12\10\1\0\2\7\17\0\2\10\1\0\10\7\1\0"+
    "\3\7\1\0\51\7\2\0\1\7\7\10\1\0\3\10\1\0\4\10"+
    "\1\7\10\0\1\10\10\0\2\7\2\10\2\0\12\10\12\0\6\7"+
    "\2\0\2\10\1\0\22\7\3\0\30\7\1\0\11\7\1\0\1\7"+
    "\2\0\7\7\3\0\1\10\4\0\6\10\1\0\1\10\1\0\10\10"+
    "\22\0\2\10\15\0\60\7\1\10\2\7\7\10\4\0\10\7\10\10"+
    "\1\0\12\10\47\0\2\7\1\0\1\7\2\0\2\7\1\0\1\7"+
    "\2\0\1\7\6\0\4\7\1\0\7\7\1\0\3\7\1\0\1\7"+
    "\1\0\1\7\2\0\2\7\1\0\4\7\1\10\2\7\6\10\1\0"+
    "\2\10\1\7\2\0\5\7\1\0\1\7\1\0\6\10\2\0\12\10"+
    "\2\0\4\7\40\0\1\7\27\0\2\10\6\0\12\10\13\0\1\10"+
    "\1\0\1\10\1\0\1\10\4\0\2\10\10\7\1\0\44\7\4\0"+
    "\24\10\1\0\2\10\5\7\13\10\1\0\44\10\11\0\1\10\71\0"+
    "\53\7\24\10\1\7\12\10\6\0\6\7\4\10\4\7\3\10\1\7"+
    "\3\10\2\7\7\10\3\7\4\10\15\7\14\10\1\7\17\10\2\0"+
    "\46\7\1\0\1\7\5\0\1\7\2\0\53\7\1\0\u014d\7\1\0"+
    "\4\7\2\0\7\7\1\0\1\7\1\0\4\7\2\0\51\7\1\0"+
    "\4\7\2\0\41\7\1\0\4\7\2\0\7\7\1\0\1\7\1\0"+
    "\4\7\2\0\17\7\1\0\71\7\1\0\4\7\2\0\103\7\2\0"+
    "\3\10\40\0\20\7\20\0\125\7\14\0\u026c\7\2\0\21\7\1\0"+
    "\32\7\5\0\113\7\3\0\3\7\17\0\15\7\1\0\4\7\3\10"+
    "\13\0\22\7\3\10\13\0\22\7\2\10\14\0\15\7\1\0\3\7"+
    "\1\0\2\10\14\0\64\7\40\10\3\0\1\7\3\0\2\7\1\10"+
    "\2\0\12\10\41\0\3\10\2\0\12\10\6\0\130\7\10\0\51\7"+
    "\1\10\1\7\5\0\106\7\12\0\35\7\3\0\14\10\4\0\14\10"+
    "\12\0\12\10\36\7\2\0\5\7\13\0\54\7\4\0\21\10\7\7"+
    "\2\10\6\0\12\10\46\0\27\7\5\10\4\0\65\7\12\10\1\0"+
    "\35\10\2\0\13\10\6\0\12\10\15\0\1\7\130\0\5\10\57\7"+
    "\21\10\7\7\4\0\12\10\21\0\11\10\14\0\3\10\36\7\15\10"+
    "\2\7\12\10\54\7\16\10\14\0\44\7\24\10\10\0\12\10\3\0"+
    "\3\7\12\10\44\7\122\0\3\10\1\0\25\10\4\7\1\10\4\7"+
    "\3\10\2\7\11\0\300\7\47\10\25\0\4\10\u0116\7\2\0\6\7"+
    "\2\0\46\7\2\0\6\7\2\0\10\7\1\0\1\7\1\0\1\7"+
    "\1\0\1\7\1\0\37\7\2\0\65\7\1\0\7\7\1\0\1\7"+
    "\3\0\3\7\1\0\7\7\3\0\4\7\2\0\6\7\4\0\15\7"+
    "\5\0\3\7\1\0\7\7\16\0\5\10\32\0\5\10\20\0\2\7"+
    "\23\0\1\7\13\0\5\10\5\0\6\10\1\0\1\7\15\0\1\7"+
    "\20\0\15\7\3\0\33\7\25\0\15\10\4\0\1\10\3\0\14\10"+
    "\21\0\1\7\4\0\1\7\2\0\12\7\1\0\1\7\3\0\5\7"+
    "\6\0\1\7\1\0\1\7\1\0\1\7\1\0\4\7\1\0\13\7"+
    "\2\0\4\7\5\0\5\7\4\0\1\7\21\0\51\7\u0a77\0\57\7"+
    "\1\0\57\7\1\0\205\7\6\0\4\7\3\10\2\7\14\0\46\7"+
    "\1\0\1\7\5\0\1\7\2\0\70\7\7\0\1\7\17\0\1\10"+
    "\27\7\11\0\7\7\1\0\7\7\1\0\7\7\1\0\7\7\1\0"+
    "\7\7\1\0\7\7\1\0\7\7\1\0\7\7\1\0\40\10\57\0"+
    "\1\7\u01d5\0\3\7\31\0\11\7\6\10\1\0\5\7\2\0\5\7"+
    "\4\0\126\7\2\0\2\10\2\0\3\7\1\0\132\7\1\0\4\7"+
    "\5\0\51\7\3\0\136\7\21\0\33\7\65\0\20\7\u0200\0\u19b6\7"+
    "\112\0\u51cd\7\63\0\u048d\7\103\0\56\7\2\0\u010d\7\3\0\20\7"+
    "\12\10\2\7\24\0\57\7\1\10\4\0\12\10\1\0\31\7\7\0"+
    "\1\10\120\7\2\10\45\0\11\7\2\0\147\7\2\0\4\7\1\0"+
    "\4\7\14\0\13\7\115\0\12\7\1\10\3\7\1\10\4\7\1\10"+
    "\27\7\5\10\20\0\1\7\7\0\64\7\14\0\2\10\62\7\21\10"+
    "\13\0\12\10\6\0\22\10\6\7\3\0\1\7\4\0\12\10\34\7"+
    "\10\10\2\0\27\7\15\10\14\0\35\7\3\0\4\10\57\7\16\10"+
    "\16\0\1\7\12\10\46\0\51\7\16\10\11\0\3\7\1\10\10\7"+
    "\2\10\2\0\12\10\6\0\27\7\3\0\1\7\1\10\4\0\60\7"+
    "\1\10\1\7\3\10\2\7\2\10\5\7\2\10\1\7\1\10\1\7"+
    "\30\0\3\7\2\0\13\7\5\10\2\0\3\7\2\10\12\0\6\7"+
    "\2\0\6\7\2\0\6\7\11\0\7\7\1\0\7\7\221\0\43\7"+
    "\10\10\1\0\2\10\2\0\12\10\6\0\u2ba4\7\14\0\27\7\4\0"+
    "\61\7\u2104\0\u016e\7\2\0\152\7\46\0\7\7\14\0\5\7\5\0"+
    "\1\7\1\10\12\7\1\0\15\7\1\0\5\7\1\0\1\7\1\0"+
    "\2\7\1\0\2\7\1\0\154\7\41\0\u016b\7\22\0\100\7\2\0"+
    "\66\7\50\0\15\7\3\0\20\10\20\0\7\10\14\0\2\7\30\0"+
    "\3\7\31\0\1\7\6\0\5\7\1\0\207\7\2\0\1\10\4\0"+
    "\1\7\13\0\12\10\7\0\32\7\4\0\1\7\1\0\32\7\13\0"+
    "\131\7\3\0\6\7\2\0\6\7\2\0\6\7\2\0\3\7\3\0"+
    "\2\7\3\0\2\7\22\0\3\10\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\1\1\5\2\6"+
    "\14\5\1\7\2\5\1\10\1\11\1\1\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\1\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\2\0\1\34\1\0\1\5\1\0\2\5\1\35"+
    "\1\36\6\5\1\37\3\5\1\40\1\41\5\5\1\34"+
    "\1\42\1\43\1\44\1\41\1\45\1\46\1\47\1\50"+
    "\1\0\3\5\1\44\14\5\1\51\2\5\1\52\1\5"+
    "\1\0\12\5\1\53\1\54\1\5\1\55\2\5\1\56"+
    "\2\5\1\34\1\0\6\5\1\57\1\60\2\5\1\61"+
    "\2\5\1\62\2\5\1\63\4\5\1\64\2\5\1\65"+
    "\1\66\1\67\4\5\1\70\1\71\3\5\1\72\1\73"+
    "\1\74\3\5\1\75";

  private static int [] zzUnpackAction() {
    int [] result = new int[170];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\71\0\253\0\71\0\344\0\u011d"+
    "\0\u0156\0\u018f\0\u01c8\0\u0201\0\u023a\0\u0273\0\u02ac\0\u02e5"+
    "\0\u031e\0\u0357\0\u0390\0\u03c9\0\u0402\0\u043b\0\71\0\u0474"+
    "\0\u04ad\0\u04e6\0\71\0\u051f\0\71\0\71\0\71\0\71"+
    "\0\71\0\71\0\71\0\71\0\71\0\u0558\0\71\0\u0591"+
    "\0\u05ca\0\u0603\0\u063c\0\u0675\0\u06ae\0\71\0\71\0\u06e7"+
    "\0\344\0\u0156\0\u04e6\0\u0720\0\u051f\0\u0759\0\u0792\0\u011d"+
    "\0\u07cb\0\u0804\0\u083d\0\u0876\0\u08af\0\u08e8\0\u0921\0\u011d"+
    "\0\u095a\0\u0993\0\u09cc\0\u011d\0\u011d\0\u0a05\0\u0a3e\0\u0a77"+
    "\0\u0ab0\0\u0ae9\0\u0b22\0\71\0\71\0\71\0\71\0\71"+
    "\0\71\0\71\0\71\0\u0b5b\0\u0b94\0\u0bcd\0\u0c06\0\u011d"+
    "\0\u0c3f\0\u0c78\0\u0cb1\0\u0cea\0\u0d23\0\u0d5c\0\u0d95\0\u0dce"+
    "\0\u0e07\0\u0e40\0\u0e79\0\u0eb2\0\u011d\0\u0eeb\0\u0f24\0\u011d"+
    "\0\u0f5d\0\u0f96\0\u0fcf\0\u1008\0\u1041\0\u107a\0\u10b3\0\u10ec"+
    "\0\u1125\0\u115e\0\u1197\0\u11d0\0\u011d\0\u011d\0\u1209\0\u011d"+
    "\0\u1242\0\u127b\0\u011d\0\u12b4\0\u12ed\0\u1326\0\u1326\0\u135f"+
    "\0\u1398\0\u13d1\0\u140a\0\u1443\0\u147c\0\u011d\0\u011d\0\u14b5"+
    "\0\u14ee\0\u011d\0\u1527\0\u1560\0\u011d\0\u1599\0\u15d2\0\u011d"+
    "\0\u160b\0\u1644\0\u167d\0\u16b6\0\u011d\0\u16ef\0\u1728\0\u011d"+
    "\0\u011d\0\u011d\0\u1761\0\u179a\0\u17d3\0\u180c\0\u011d\0\u011d"+
    "\0\u1845\0\u187e\0\u18b7\0\u011d\0\u011d\0\u011d\0\u18f0\0\u1929"+
    "\0\u1962\0\u011d";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[170];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\10\1\2"+
    "\1\11\1\12\1\13\2\10\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\10\1\24\1\10\1\25"+
    "\1\10\1\26\3\10\1\27\1\30\1\31\1\32\1\10"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\73\0\1\4\73\0"+
    "\1\60\63\0\1\61\1\3\1\4\66\61\7\0\30\10"+
    "\1\0\2\10\1\0\1\10\36\0\2\62\27\0\1\63"+
    "\37\0\2\12\27\0\1\63\35\0\5\10\1\64\22\10"+
    "\1\0\2\10\1\0\1\10\34\0\30\10\1\0\2\10"+
    "\1\0\1\10\1\0\1\65\32\0\7\10\1\66\2\10"+
    "\1\67\2\10\1\70\12\10\1\0\2\10\1\0\1\10"+
    "\34\0\12\10\1\71\1\72\14\10\1\0\2\10\1\0"+
    "\1\10\34\0\20\10\1\73\7\10\1\0\2\10\1\0"+
    "\1\10\34\0\4\10\1\74\23\10\1\0\2\10\1\0"+
    "\1\10\34\0\20\10\1\75\7\10\1\0\2\10\1\0"+
    "\1\10\34\0\11\10\1\76\5\10\1\77\1\100\7\10"+
    "\1\0\2\10\1\0\1\10\34\0\10\10\1\101\6\10"+
    "\1\102\1\103\7\10\1\0\2\10\1\0\1\10\34\0"+
    "\12\10\1\104\4\10\1\105\4\10\1\106\3\10\1\0"+
    "\2\10\1\0\1\10\34\0\23\10\1\107\4\10\1\0"+
    "\2\10\1\0\1\10\34\0\12\10\1\110\15\10\1\0"+
    "\2\10\1\0\1\10\34\0\10\10\1\111\17\10\1\0"+
    "\2\10\1\0\1\10\34\0\7\10\1\112\20\10\1\0"+
    "\2\10\1\0\1\10\36\0\2\113\56\0\45\65\1\114"+
    "\23\65\63\0\1\115\66\0\1\116\71\0\1\117\71\0"+
    "\1\120\70\0\1\121\70\0\1\122\70\0\1\123\5\0"+
    "\5\60\1\124\63\60\7\0\6\10\1\125\2\10\1\126"+
    "\16\10\1\0\2\10\1\0\1\10\34\0\7\10\1\127"+
    "\20\10\1\0\2\10\1\0\1\10\34\0\25\10\1\130"+
    "\2\10\1\0\2\10\1\0\1\10\34\0\15\10\1\131"+
    "\12\10\1\0\2\10\1\0\1\10\34\0\6\10\1\132"+
    "\4\10\1\133\14\10\1\0\2\10\1\0\1\10\34\0"+
    "\15\10\1\134\7\10\1\135\2\10\1\0\2\10\1\0"+
    "\1\10\34\0\7\10\1\136\20\10\1\0\2\10\1\0"+
    "\1\10\34\0\21\10\1\137\6\10\1\0\2\10\1\0"+
    "\1\10\34\0\21\10\1\140\6\10\1\0\2\10\1\0"+
    "\1\10\34\0\24\10\1\141\3\10\1\0\2\10\1\0"+
    "\1\10\34\0\7\10\1\142\20\10\1\0\2\10\1\0"+
    "\1\10\34\0\20\10\1\143\7\10\1\0\2\10\1\0"+
    "\1\10\34\0\17\10\1\144\10\10\1\0\2\10\1\0"+
    "\1\10\34\0\15\10\1\145\12\10\1\0\2\10\1\0"+
    "\1\10\34\0\4\10\1\146\23\10\1\0\2\10\1\0"+
    "\1\10\34\0\11\10\1\147\16\10\1\0\2\10\1\0"+
    "\1\10\34\0\17\10\1\150\10\10\1\0\2\10\1\0"+
    "\1\10\34\0\20\10\1\151\7\10\1\0\2\10\1\0"+
    "\1\10\36\0\2\113\1\152\27\0\1\152\25\0\4\60"+
    "\1\4\1\124\63\60\7\0\7\10\1\153\20\10\1\0"+
    "\2\10\1\0\1\10\34\0\13\10\1\154\14\10\1\0"+
    "\2\10\1\0\1\10\34\0\26\10\1\155\1\10\1\0"+
    "\2\10\1\0\1\10\34\0\4\10\1\156\23\10\1\0"+
    "\2\10\1\0\1\10\34\0\17\10\1\157\10\10\1\0"+
    "\2\10\1\0\1\10\34\0\24\10\1\160\3\10\1\0"+
    "\2\10\1\0\1\10\34\0\11\10\1\161\16\10\1\0"+
    "\2\10\1\0\1\10\34\0\4\10\1\162\23\10\1\0"+
    "\2\10\1\0\1\10\34\0\4\10\1\163\23\10\1\0"+
    "\2\10\1\0\1\10\34\0\6\10\1\164\21\10\1\0"+
    "\2\10\1\0\1\10\34\0\4\10\1\165\23\10\1\0"+
    "\2\10\1\0\1\10\34\0\4\10\1\166\23\10\1\0"+
    "\2\10\1\0\1\10\34\0\13\10\1\167\14\10\1\0"+
    "\2\10\1\0\1\10\34\0\21\10\1\170\6\10\1\0"+
    "\2\10\1\0\1\10\34\0\4\10\1\171\3\10\1\172"+
    "\17\10\1\0\2\10\1\0\1\10\34\0\12\10\1\173"+
    "\15\10\1\0\2\10\1\0\1\10\34\0\20\10\1\174"+
    "\7\10\1\0\2\10\1\0\1\10\34\0\27\10\1\175"+
    "\1\0\2\10\1\0\1\10\36\0\2\176\31\0\1\177"+
    "\1\0\1\177\31\0\10\10\1\200\17\10\1\0\2\10"+
    "\1\0\1\10\34\0\15\10\1\201\12\10\1\0\2\10"+
    "\1\0\1\10\34\0\12\10\1\202\15\10\1\0\2\10"+
    "\1\0\1\10\34\0\17\10\1\203\10\10\1\0\2\10"+
    "\1\0\1\10\34\0\20\10\1\204\7\10\1\0\2\10"+
    "\1\0\1\10\34\0\27\10\1\205\1\0\2\10\1\0"+
    "\1\10\34\0\12\10\1\206\15\10\1\0\2\10\1\0"+
    "\1\10\34\0\13\10\1\207\14\10\1\0\2\10\1\0"+
    "\1\10\34\0\14\10\1\210\13\10\1\0\2\10\1\0"+
    "\1\10\34\0\24\10\1\211\3\10\1\0\2\10\1\0"+
    "\1\10\34\0\4\10\1\212\23\10\1\0\2\10\1\0"+
    "\1\10\34\0\10\10\1\213\17\10\1\0\2\10\1\0"+
    "\1\10\34\0\7\10\1\214\20\10\1\0\2\10\1\0"+
    "\1\10\34\0\12\10\1\215\15\10\1\0\2\10\1\0"+
    "\1\10\34\0\10\10\1\216\17\10\1\0\2\10\1\0"+
    "\1\10\36\0\2\176\65\0\11\10\1\217\16\10\1\0"+
    "\2\10\1\0\1\10\34\0\13\10\1\220\14\10\1\0"+
    "\2\10\1\0\1\10\34\0\20\10\1\221\7\10\1\0"+
    "\2\10\1\0\1\10\34\0\13\10\1\222\14\10\1\0"+
    "\2\10\1\0\1\10\34\0\6\10\1\223\21\10\1\0"+
    "\2\10\1\0\1\10\34\0\13\10\1\224\14\10\1\0"+
    "\2\10\1\0\1\10\34\0\15\10\1\225\12\10\1\0"+
    "\2\10\1\0\1\10\34\0\15\10\1\226\12\10\1\0"+
    "\2\10\1\0\1\10\34\0\14\10\1\227\13\10\1\0"+
    "\2\10\1\0\1\10\34\0\7\10\1\230\20\10\1\0"+
    "\2\10\1\0\1\10\34\0\7\10\1\231\20\10\1\0"+
    "\2\10\1\0\1\10\34\0\12\10\1\232\15\10\1\0"+
    "\2\10\1\0\1\10\34\0\25\10\1\233\2\10\1\0"+
    "\2\10\1\0\1\10\34\0\4\10\1\234\23\10\1\0"+
    "\2\10\1\0\1\10\34\0\13\10\1\235\14\10\1\0"+
    "\2\10\1\0\1\10\34\0\4\10\1\236\23\10\1\0"+
    "\2\10\1\0\1\10\34\0\4\10\1\237\23\10\1\0"+
    "\2\10\1\0\1\10\34\0\23\10\1\240\4\10\1\0"+
    "\2\10\1\0\1\10\34\0\4\10\1\241\23\10\1\0"+
    "\2\10\1\0\1\10\34\0\14\10\1\242\13\10\1\0"+
    "\2\10\1\0\1\10\34\0\24\10\1\243\3\10\1\0"+
    "\2\10\1\0\1\10\34\0\15\10\1\244\12\10\1\0"+
    "\2\10\1\0\1\10\34\0\13\10\1\245\14\10\1\0"+
    "\2\10\1\0\1\10\34\0\15\10\1\246\12\10\1\0"+
    "\2\10\1\0\1\10\34\0\27\10\1\247\1\0\2\10"+
    "\1\0\1\10\34\0\13\10\1\250\14\10\1\0\2\10"+
    "\1\0\1\10\34\0\4\10\1\251\23\10\1\0\2\10"+
    "\1\0\1\10\34\0\15\10\1\252\12\10\1\0\2\10"+
    "\1\0\1\10\25\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6555];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\1\1\1\11\20\1\1\11"+
    "\3\1\1\11\1\1\11\11\1\1\1\11\6\1\2\11"+
    "\2\0\1\1\1\0\1\1\1\0\26\1\10\11\1\0"+
    "\25\1\1\0\24\1\1\0\53\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[170];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
int token;
Object semanticValue;
int line(){return yyline;}
int column(){return yycolumn;}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2252) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 41: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [42] { return token=OUT; }");
          { return token=OUT;
          }
        case 62: break;
        case 27: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [110] { return token=\',\'; }");
          { return token=',';
          }
        case 63: break;
        case 22: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [103] { return token=\'=\'; }");
          { return token='=';
          }
        case 64: break;
        case 49: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [46] { return token=FALSE; }");
          { return token=FALSE;
          }
        case 65: break;
        case 55: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [33] { return token=EXPLAIN; }");
          { return token=EXPLAIN;
          }
        case 66: break;
        case 5: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [77] { semanticValue=yytext();return token=IDENTIFIER; }");
          { semanticValue=yytext();return token=IDENTIFIER;
          }
        case 67: break;
        case 48: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [43] { return token=NODES; }");
          { return token=NODES;
          }
        case 68: break;
        case 7: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [63] { return token=\'\\\\\'; }");
          { return token='\\';
          }
        case 69: break;
        case 10: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [80] { return token=\'+\'; }");
          { return token='+';
          }
        case 70: break;
        case 56: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [67] { return token=COMPUTE; }");
          { return token=COMPUTE;
          }
        case 71: break;
        case 57: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [55] { return token=FOR_EACH; }");
          { return token=FOR_EACH;
          }
        case 72: break;
        case 23: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [104] { return token=\'<\'; }");
          { return token='<';
          }
        case 73: break;
        case 54: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [66] { return token=GLOBAL; }");
          { return token=GLOBAL;
          }
        case 74: break;
        case 40: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [102] { return token=ASSIGN; }");
          { return token=ASSIGN;
          }
        case 75: break;
        case 12: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [85] { return token=\'^\'; }");
          { return token='^';
          }
        case 76: break;
        case 1: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [118] { throw new Error(\"unexpected\"+yytext()); }");
          { throw new Error("unexpected"+yytext());
          }
        case 77: break;
        case 4: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [83] { return token=\'*\'; }");
          { return token='*';
          }
        case 78: break;
        case 32: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [41] { return token=ON; }");
          { return token=ON;
          }
        case 79: break;
        case 53: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [54] { return token=FOR_ALL; }");
          { return token=FOR_ALL;
          }
        case 80: break;
        case 26: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [109] { return token=\';\'; }");
          { return token=';';
          }
        case 81: break;
        case 36: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [94] { return token=AND; }");
          { return token=AND;
          }
        case 82: break;
        case 19: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [92] { return token=\'!\'; }");
          { return token='!';
          }
        case 83: break;
        case 34: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [75] { semanticValue=yytext(); return STRING_LITERAL; }");
          { semanticValue=yytext(); return STRING_LITERAL;
          }
        case 84: break;
        case 18: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [91] { return token=\']\'; }");
          { return token=']';
          }
        case 85: break;
        case 31: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [40] { return token=TO; }");
          { return token=TO;
          }
        case 86: break;
        case 14: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [87] { return token=\')\'; }");
          { return token=')';
          }
        case 87: break;
        case 25: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [108] { return token=\':\'; }");
          { return token=':';
          }
        case 88: break;
        case 35: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [98] { return token=NEQ; }");
          { return token=NEQ;
          }
        case 89: break;
        case 37: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [99] { return token=EQ; }");
          { return token=EQ;
          }
        case 90: break;
        case 59: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [44] { return token=ALL_NODES; }");
          { return token=ALL_NODES;
          }
        case 91: break;
        case 6: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [72] { semanticValue=Long.parseLong(yytext());return token=INTEGER_LITERAL; }");
          { semanticValue=Long.parseLong(yytext());return token=INTEGER_LITERAL;
          }
        case 92: break;
        case 13: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [86] { return token=\'(\'; }");
          { return token='(';
          }
        case 93: break;
        case 51: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [53] { return token=EXISTS; }");
          { return token=EXISTS;
          }
        case 94: break;
        case 50: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [61] { return token=UNION; }");
          { return token=UNION;
          }
        case 95: break;
        case 39: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [101] { return token=GEQ; }");
          { return token=GEQ;
          }
        case 96: break;
        case 58: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [58] { return token=IS_SUBSET; }");
          { return token=IS_SUBSET;
          }
        case 97: break;
        case 17: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [90] { return token=\'[\'; }");
          { return token='[';
          }
        case 98: break;
        case 38: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [100] { return token=LEQ; }");
          { return token=LEQ;
          }
        case 99: break;
        case 45: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [35] { return token=FROM; }");
          { return token=FROM;
          }
        case 100: break;
        case 16: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [89] { return token=\'}\'; }");
          { return token='}';
          }
        case 101: break;
        case 61: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [59] { return token=IS_PROPER_SUBSET; }");
          { return token=IS_PROPER_SUBSET;
          }
        case 102: break;
        case 3: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [84] { return token=\'/\'; }");
          { return token='/';
          }
        case 103: break;
        case 47: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [57] { return token=NOT_IN; }");
          { return token=NOT_IN;
          }
        case 104: break;
        case 46: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [37] { return token=WHEN; }");
          { return token=WHEN;
          }
        case 105: break;
        case 44: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [45] { return token=TRUE; }");
          { return token=TRUE;
          }
        case 106: break;
        case 21: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [106] { return token=\'|\'; }");
          { return token='|';
          }
        case 107: break;
        case 8: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [107] { return token=\'.\'; }");
          { return token='.';
          }
        case 108: break;
        case 52: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [34] { return token=SELECT; }");
          { return token=SELECT;
          }
        case 109: break;
        case 20: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [93] { return token=\'?\'; }");
          { return token='?';
          }
        case 110: break;
        case 11: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [81] { return token=\'%\'; }");
          { return token='%';
          }
        case 111: break;
        case 60: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [62] { return token=INTERSECT; }");
          { return token=INTERSECT;
          }
        case 112: break;
        case 42: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [65] { return token=VAR; }");
          { return token=VAR;
          }
        case 113: break;
        case 15: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [88] { return token=\'{\'; }");
          { return token='{';
          }
        case 114: break;
        case 9: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [82] { return token=\'-\'; }");
          { return token='-';
          }
        case 115: break;
        case 29: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [38] { return token=AT; }");
          { return token=AT;
          }
        case 116: break;
        case 24: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [105] { return token=\'>\'; }");
          { return token='>';
          }
        case 117: break;
        case 28: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [73] { semanticValue=Double.parseDouble(yytext());return FLOAT_LITERAL; }");
          { semanticValue=Double.parseDouble(yytext());return FLOAT_LITERAL;
          }
        case 118: break;
        case 43: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [39] { return token=TIME; }");
          { return token=TIME;
          }
        case 119: break;
        case 33: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [51] { return token=OR; }");
          { return token=OR;
          }
        case 120: break;
        case 30: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [56] { return token=IN; }");
          { return token=IN;
          }
        case 121: break;
        case 2: 
          //System.out.println("match: --"+yytext()+"--");
          //System.out.println("action [116] {  }");
          { 
          }
        case 122: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {
                //System.out.println("match: <<EOF>>");
                //System.out.println("action [117] { return token=ENDINPUT; }");
                return token=ENDINPUT;
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      //System.out.println("Usage : java Scanner <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        Scanner scanner = null;
        try {
          scanner = new Scanner( new java.io.FileReader(argv[i]) );
          do {
            //System.out.println(scanner.yylex());
          } while (!scanner.zzAtEOF);

        }
        catch (java.io.FileNotFoundException e) {
          //System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          //System.out.println("IO error scanning file \""+argv[i]+"\"");
          //System.out.println(e);
        }
        catch (Exception e) {
          //System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
